// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_3_2.Models;

#nullable disable

namespace Mission08_3_2.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission08_3_2.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Church"
                        });
                });

            modelBuilder.Entity("Mission08_3_2.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskItemId = 1,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 1,
                            TaskName = "Pay bills"
                        },
                        new
                        {
                            TaskItemId = 2,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 1,
                            TaskName = "Study for exam"
                        },
                        new
                        {
                            TaskItemId = 3,
                            CategoryId = 1,
                            Completed = false,
                            Quadrant = 2,
                            TaskName = "Plan family vacation"
                        },
                        new
                        {
                            TaskItemId = 4,
                            CategoryId = 3,
                            Completed = false,
                            DueDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 2,
                            TaskName = "Finish project proposal"
                        },
                        new
                        {
                            TaskItemId = 5,
                            CategoryId = 3,
                            Completed = false,
                            DueDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quadrant = 3,
                            TaskName = "Reply to emails"
                        },
                        new
                        {
                            TaskItemId = 6,
                            CategoryId = 1,
                            Completed = false,
                            Quadrant = 4,
                            TaskName = "Browse social media"
                        });
                });

            modelBuilder.Entity("Mission08_3_2.Models.TaskItem", b =>
                {
                    b.HasOne("Mission08_3_2.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Mission08_3_2.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
